[package]
name = "allsorts"
version = "0.1.0"
authors = ["YesLogic Pty. Ltd. <info@yeslogic.com>"]
edition = "2018"
publish = false

documentation = "https://docs.rs/crate/allsorts"
repository = "https://github.com/yeslogic/allsorts"

readme = "README.md"
license = "Apache-2.0"

keywords = ["font", "shaping", "opentype", "truetype", "parse"]
categories = ["text-processing"]

[badges]
travis-ci = { repository = "yeslogic/allsorts" }

[dependencies]
bitflags = "1.0"
brotli-decompressor = "2.3"
byteorder = "1.2"
encoding_rs = "0.8.16"
flate2 = { version = "1.0", default-features = false, features = ["zlib"] }
itertools = "0.8"
lazy_static = "1.3.0"
libc = "0.2"
log = "0.4"
num = "0.2"

[dev-dependencies]
criterion = "0.2"
regex = "1.1.6"

[[bench]]
name = "bench-shape"
harness = false

[[bench]]
name = "bench-read"
harness = false

[features]
prince = []
